version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: dockette/adminer
    ports:
      - 8080:80
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "cfauvel.dev@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminP@ssw0rd!"

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_HOST: localhost
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
      PG_PORT: $PG_PORT
    env_file:
      - .env
    ports:
      - "4000:4000"

volumes:
  pgdata:
