networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local

services:
  # PostgreSQL
  nls-postgres:
    image: postgres:16.9-bullseye
    container_name: nls-postgres
    restart: unless-stopped
    ports:
      - "$PG_PORT:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PGPASSWORD: $PG_PASSWORD
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
    networks:
      - postgres-network
  adminer:
    image: adminer:5.2.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - postgres-network
