info:
  contact: {}
  description: API de messagerie sécurisée par JWT
  title: API Messaging
  version: "1.0"
paths:
  /ws/{threadId}:
    get:
      description: Ouvre une connexion WebSocket sur un thread
      parameters:
      - description: ID du thread
        in: path
        name: threadId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "101":
          description: Switching Protocols
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: WebSocket protégé par JWT
      tags:
      - ws
securityDefinitions:
  BearerAuth:
    description: 'Type "Bearer" suivi d''un espace et de votre token JWT. Exemple :
      "Bearer {token}"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
